model_family: phi
LoRA:
  r: 0
  alpha: 32
  dropout: 0.05
data_path: locuslab/TOFU
split: retain99
batch_size: 4
gradient_accumulation_steps: 4
num_epochs: 10
lr: 5.0e-05
save_dir: checkpoints/Traditional_RT_on_${split}_data_epoch${num_epochs}_lr${lr}_${model_family}_wd${weight_decay}
weight_decay: 0.01
seed: 42
