model_family: phi
resume_from: /data/urveim/talmahmud/UnReLDP/checkpoints/SISA/SISA_ITr_R_4slices_epoch_10_phi/shard4_3
data_paths:
- talmahmud/tofu_custom_split_UnReLDP
splits:
- retain_shard4_4_forget02
num_shards: 4
forget: forget02
batch_size: 4
gradient_accumulation_steps: 4
num_epochs: 10
lr: 5.0e-05
weight_decay: 0.01
seed: 42
data_dir: ${oc.env:DATA}
save_dir: ${data_dir}/UnReLDP/checkpoints/SISA/SISA_ITr_R_${num_shards}slices_epoch_${num_epochs}_phi
continual:
  osl:
    mrr: 0.1
    trr: 0.85
    cali_batches: 4
    target_linear_only: true
