retain_result: checkpoints/RFS_on_retain90_data_epoch6_lr5e-05_llama2-7b_wd0.01/eval_results/ds_size300/eval_log_aggregated.json
ckpt_result: checkpoints/UM_FT_BM_dp_MLM_on_retain90_epoch_3_lr_5e-05_llama2-7b_wd_0.01_eps_0.5/eval_results/ds_size300/eval_log_aggregated.json
method_name: UM_FT_BM_dp_MLM_on_retain90_epoch_3_lr_5e-05_llama2-7b_wd_0.01_eps_0.5
submitted_by: tamim
save_file: results/UM_FT_BM_dp_MLM_on_retain90_epoch_3_lr_5e-05_llama2-7b_wd_0.01_eps_0.5.csv