model_family: phi  

base_model_dir: checkpoints/BM_dp_MLM_Tr_on_full_data_epoch10_lr5e-05_phi_wd0.01_eps_1.0

# Base model and eps extracted from base_model_dir
base_model_name: ${extracted_base_model}  
eps: ${extracted_eps}  

# LoRA configurations (optional)
LoRA:
  r: 0
  alpha: 32
  dropout: 0.05

data_path: locuslab/TOFU
split: full

batch_size: 4
gradient_accumulation_steps: 4

num_epochs: 5
lr: 5e-5

save_dir: checkpoints/UM_FT_${base_model_name}_on_${split}_epoch_${num_epochs}_lr_${lr}_${model_family}_wd_${weight_decay}_eps_${eps}

# Weight decay and seed for reproducibility
weight_decay: 0.01
seed: 42
