model_family: phi

data_path: locuslab/TOFU
split: full  
batch_size: 16
#gradient_accumulation_steps: 4 #Poisson sampling, which is often used in differential privacy algorithms like Opacus, is not compatible with gradient accumulation.
num_epochs: 10

# Training configurations
lr: 5e-5  
max_grad_norm: 1.0  
target_epsilon: 0.5  
target_delta: 1e-12 
weight_decay: 0.01
save_dir: checkpoints/BM_dp_SGD_Tr_on_${split}_data_epoch_${num_epochs}_lr_${lr}_${model_family}_wd_${weight_decay}_delta_${target_delta}_eps_${target_epsilon}

# Seed for reproducibility
seed: 42


