model_family: phi
lora: ''
LoRA:
  r: 0
  alpha: 32
  dropout: 0.05
data_path: null
split: full
batch_size: 4
gradient_accumulation_steps: 4
num_epochs: 10
lr: 5.0e-05
weight_decay: 0.01
seed: 42
target_epsilon: 25
dp_type: noun_phrase
save_dir: checkpoints/our_dp_${dp_type}_ft_epoch${num_epochs}_lr${lr}_${model_family}_${split}_wd${weight_decay}_eps_${target_epsilon}.0
