retain_result: /data/urveim/talmahmud/UnReLDP1/checkpoints/pretrained Qwen/eval_results/ds_size400/eval_log_aggregated.json
#model_path: /data/urveim/talmahmud/UnReLDP1/checkpoints/ep25/EP25_UnReLDP_shard_P50_R50DPEP25_epoch_8_lr_5e-05_qwen3-4b
#ckpt_result: ${model_path}/eval_results/ds_size400/eval_log_aggregated.json
ckpt_result: /data/urveim/talmahmud/UnReLDP1/checkpoints/pretrained Qwen/eval_results/ds_size400/eval_log_aggregated.json
method_name: Final_Model_full
submitted_by: tamim
save_file: results/pretrained Qwen.csv