model_family: phi
num_shards: 2
EP: 50.0
resume_from: /data/urveim/talmahmud/ESU/checkpoints/ep50.0/EP50.0UM_UnReLDP_P50_BM_E8_Rshards_2_epoch_5_lr_5e-05_phi_mrr0.1_trr0.85_cali4/shard2_1
data_paths:
- talmahmud/tofu_custom_split_ESU
splits:
- retain_shard2_2_forget10
forget: forget10
batch_size: 4
gradient_accumulation_steps: 4
num_epochs: 5
lr: 5.0e-05
weight_decay: 0.01
seed: 42
save_dir: /data/urveim/talmahmud/ESU/checkpoints/ep50.0/EP50.0UM_UnReLDP_P50_BM_E8_Rshards_2_epoch_5_lr_5e-05_phi_mrr0.1_trr0.85_cali4
continual:
  osl:
    mrr: 0.1
    trr: 0.85
    cali_batches: 4
    target_linear_only: true
