model_family: phi
num_shards: 2
EP: 1.0
resume_from: /data/urveim/talmahmud/ESU/checkpoints/ep1.0/EP1.0_UnReLDP_shard_P50R50DP_EP1.0_epoch_10_lr_5e-05_phi
data_paths:
- talmahmud/tofu_custom_split_ESU
- talmahmud/tofu_custom_split_ESU
- talmahmud/tofu_custom_split_ESU
splits:
- shard_P50
- shard2_1
- shard2_2
forget: full
batch_size: 4
gradient_accumulation_steps: 4
num_epochs: 5
lr: 5.0e-05
weight_decay: 0.01
seed: 42
save_dir: /data/urveim/talmahmud/ESU/checkpoints/ep${EP}/EP${EP}UM_UnReLDP_P50_BM_E8_Rshards_${num_shards}_epoch_${num_epochs}_lr_5e-05_${model_family}_mrr${continual.osl.mrr}_trr${continual.osl.trr}_cali${continual.osl.cali_batches}
continual:
  osl:
    mrr: 0.1
    trr: 0.85
    cali_batches: 4
    target_linear_only: true
