model_family: phi
resume_from: None
data_paths:
- talmahmud/tofu_custom_split_UnReLDP
- talmahmud/tofu_custom_split_UnReLDP
- talmahmud/tofu_custom_split_UnReLDP
- talmahmud/tofu_custom_split_UnReLDP
splits:
- shard4_1
- shard4_2
- shard4_3
- shard4_4
num_shards: 4
batch_size: 4
gradient_accumulation_steps: 4
num_epochs: 10
lr: 5.0e-05
weight_decay: 0.01
seed: 42
data_dir: ${oc.env:DATA}
save_dir: ${data_dir}/UnReLDP/checkpoints/SISA/SISA_ITr_R_${num_shards}slices_epoch_${num_epochs}_${model_family}
continual:
  osl:
    mrr: 0.1
    trr: 0.85
    cali_batches: 4
    target_linear_only: true
